### ISSUE TITLE
Flat out won't work. file missing: RealESRGAN_x2plus.pth

### ISSUE THREAD

**Issue by PhoenixStormJr** [KVignesh122/image-enhancement#1]
file missing: RealESRGAN_x2plus.pth when running

**Comment by KVignesh122** [comment]
The instructions are mentioned in the notebook:

"Download either RealESRGAN_x2plus.pth or RealESRGAN_x4plus.pth (or both of them) from [this model zoo](https://github.com/NightmareAI/Real-ESRGAN/blob/master/docs/model_zoo.md)."
